### ISSUE TITLE
Return specific fields for the canographia instance

### ISSUE THREAD

**Issue by Pipazoul** [datatlas-erasme/front#56] opened 2022-03-17 10:53 UTC
Some wp fields are not returned and needed for a display on the front

- type
- status (a mapping is needed between the machine name of the subfields and the human readable name)
  - status2 => J'ai envie de réaliser ce projet
  - status3 => J'ai déjà commencé ce projet
  - status4 => J'ai terminé ce projet

- tags (returned as an array ? ex : ["tag1", "tag2", "tag3"] )

**Comment by Pipazoul** [comment] 2022-03-18 10:24
> I have a `status1` in the data. What is it supposed to be mapped to ? @Pipazoul

I think that this post is an old one who is not supposed to exist anymore, you can probably skip it for now

**Comment by racine-p-a** [comment] 2022-04-13 13:24
@Pipazoul It has been done a long time ago. Does it work as intended ? If so, I'll let you close this issue.

**Closed** 2022-04-25 13:39 UTC
Labels: instance configuration, back, priority high, wordpress, canographia
